"""add pokemon rpg trainer and pokemon tables

Revision ID: e513f4bf2c3a
Revises: 
Create Date: 2026-09-26 02:03:02.603030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e513f4bf2c3a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon_rpg_trainers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('whatsapp_id', sa.String(), nullable=False),
    sa.Column('pokebolas', sa.Integer(), nullable=False),
    sa.Column('moedas', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pokemon_rpg_trainers_whatsapp_id'), 'pokemon_rpg_trainers', ['whatsapp_id'], unique=True)
    op.create_table('pokemon_rpg_pokemons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['trainer_id'], ['pokemon_rpg_trainers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pokemon_rpg_pokemons_trainer_id'), 'pokemon_rpg_pokemons', ['trainer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pokemon_rpg_pokemons_trainer_id'), table_name='pokemon_rpg_pokemons')
    op.drop_table('pokemon_rpg_pokemons')
    op.drop_index(op.f('ix_pokemon_rpg_trainers_whatsapp_id'), table_name='pokemon_rpg_trainers')
    op.drop_table('pokemon_rpg_trainers')
    # ### end Alembic commands ###
